### ISSUE TITLE
Dinduks error

### ISSUE THREAD

**Issue by MartinRioux72** [Dinduks/Lastfm-Top-Albums#3]
I get this error when using your program, just wanted to let you know. 
Martin

Fatal error: Call to a member function getElementsByTagName() on a non-object in /home/dinduks/

**Comment by Dinduks** [comment]
Does it still happen?

**Comment by MartinRioux72** [comment]
Lol I don’t even know what the problem was now, it’s been a while

**Comment by Dinduks** [comment]
:smile: 

I think I know what the problem was, and it doesn't happen anymore.
