### ISSUE TITLE
Releasing a fork under GPL v3

### ISSUE THREAD

**Issue by Like-all** [Dinduks/Lastfm-Top-Albums#5]
Hi there!

I have some plans to develop and release [my fork](https://github.com/Like-all/last-nine) under the terms and conditions of GPL v3 license. The forked source code tree was not distributed under terms and conditions of any license, therefore I cannot proceed without requesting your permission.

Thanks in advance, and have a great day!

Best regards,
Azer.

**Comment by Dinduks** [comment]
Hi. No problem. Why not update this repo?

**Comment by Like-all** [comment]
Even better! I'll prepare my changes and submit a pull request.
